name: Coverage Badge
on:
  push:
    branches:
    - master
jobs:
  release:
    name: coverage-badge
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Lint And Build
      run: npm run build

    - name: Run Tests
      run: npm run test

    - name: Make Coverage Badge
      uses: action-badges/cobertura-coverage-xml-badges@0.2.1
      with:
        file-name: coverage.svg
        badge-branch: badges
        github-token: ${{ secrets.GITHUB_TOKEN }}
        coverage-file-name: ./coverage/cobertura-coverage.xml
